version: '3'

services:
  app:
    image: alyonamoskalets/glpi:debian
    restart: always
    ports:
      - '80:80'
      - '443:443'
  mysql:
    image: mariadb
    restart: always
    ports:
    - '3306:3306'
    volumes:
      - /glpi/db:/var/lib/mysql
    environment:
      - MARIADB_USER=inventory_user
      - MARIADB_PASSWORD=pass4DB
      - MARIADB_DATABASE=inventory
      - MARIADB_ROOT_PASSWORD=pass4Admin
      - MARIADB_PORT_NUMBER=3306
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    links:
      - mysql